"""The repo's own `.agents/` shared set must stay in sync with `templates/` (PI-685).

This repo dogfoods the lifecycle infrastructure it ships. It is not a scaffolded
project, so a declared shared set (`tools/sync_agents_from_templates.py`) is
kept byte-identical to its template sources instead — the same derived-copy
pattern as the `plugins/` payload and the `.claude/` mirror. An audit (epic
#677) found the repo's own guard hooks had silently fallen behind the templates;
this test makes that class of drift a CI failure.

Also guards the committed CODE_MAP: `.agents/docs/CODE_MAP.md` is generated by
the (synced) `gen_code_map.py` and advertised as "read this before grepping" —
a stale map misleads agents, so regeneration must produce the committed bytes.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import tools.sync_agents_from_templates as semi

REPO_ROOT = Path(__file__).resolve().parents[2]


def test_shared_set_is_in_sync():
    # SYNCED files byte-equal their template sources; DIVERGED entries still
    # actually differ (stale allowlist detection); NOT_ADOPTED stay absent.
    problems = semi.check()
    assert not problems, (
        "run `uv run python tools/sync_agents_from_templates.py` (then `just sync-claude`) "
        f"or reclassify: {problems}"
    )


def test_manifest_covers_no_phantom_sources():
    # Every template source named in the manifest must exist — a moved or
    # deleted template file must be reflected here, not silently skipped.
    for spec in semi.SYNCED.values():
        src = spec[0] if isinstance(spec, tuple) else spec
        assert (semi.TEMPLATES / src).exists(), f"SYNCED source missing: templates/{src}"
    for src, _reason in semi.DIVERGED.values():
        assert (semi.TEMPLATES / src).exists(), f"DIVERGED source missing: templates/{src}"


def test_diverged_entries_carry_reasons():
    for dest, (_src, reason) in {**semi.DIVERGED, **semi.NOT_ADOPTED}.items():
        assert len(reason) > 20, f"allowlist entry needs a real reason: {dest}"


def test_committed_code_map_is_fresh(tmp_path: Path):
    # Regenerating the code map from the current sources must reproduce the
    # committed file — otherwise the "read this before grepping" index lies.
    committed = REPO_ROOT / ".agents" / "docs" / "CODE_MAP.md"
    assert committed.exists(), "run `just code-map` and commit .agents/docs/CODE_MAP.md"
    subprocess.run(
        [
            sys.executable,
            str(REPO_ROOT / ".agents" / "scripts" / "gen_code_map.py"),
            str(REPO_ROOT / "src"),
        ],
        cwd=tmp_path,
        check=True,
        capture_output=True,
    )
    fresh = (tmp_path / ".agents" / "docs" / "CODE_MAP.md").read_bytes()
    assert fresh == committed.read_bytes(), (
        "CODE_MAP.md is stale — run `just code-map` (and `just sync-claude`) and commit"
    )
