"""The repo's own `.claude/` must stay a faithful mirror of `.agents/` (PI-627).

Claude Code reads project config from `.claude/` only, so this repo carries a
committed `.claude/` mirror of the `.agents/` entries it commits — otherwise its
own guard hooks and skills would never load in a Claude Code session. The mirror
is generated by `tools/sync_claude_dir.py` (`just sync-claude`); this test fails
CI if the committed copy drifts, exactly like the `plugins/` payload check.
"""

from __future__ import annotations

import hashlib
import shutil
from pathlib import Path

import tools.sync_claude_dir as sync_claude_dir

REPO_ROOT = Path(__file__).resolve().parents[2]


def _tree_hashes(root: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    for p in sorted(root.rglob("*")):
        if not p.is_file() or "__pycache__" in p.parts or p.suffix == ".pyc":
            continue
        out[p.relative_to(root).as_posix()] = hashlib.sha256(p.read_bytes()).hexdigest()
    return out


def test_committed_claude_matches_a_fresh_sync(tmp_path: Path):
    # Seed a throwaway repo with the real .agents/, sync, and compare its .claude/
    # to the committed one byte-for-byte.
    shutil.copytree(
        REPO_ROOT / ".agents",
        tmp_path / ".agents",
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
    )
    sync_claude_dir.sync(tmp_path)

    fresh = _tree_hashes(tmp_path / ".claude")
    committed = _tree_hashes(REPO_ROOT / ".claude")

    added = sorted(set(fresh) - set(committed))
    removed = sorted(set(committed) - set(fresh))
    assert not added and not removed, (
        f"run `just sync-claude` and commit — added={added} removed={removed}"
    )
    drifted = sorted(p for p in committed if fresh[p] != committed[p])
    assert not drifted, f"run `just sync-claude` and commit — drifted={drifted}"


def test_mirror_set_tracks_the_gitignore_allowlist():
    # MIRRORED must equal the `.agents/` entries the repo commits (the
    # `!.agents/...` un-ignore lines), so the two can't silently diverge.
    # A dir un-ignored only to re-expose a nested file (`!.agents/docs` followed
    # by `.agents/docs/*`) is a plumbing line, not a committed entry — the
    # committed entry is the nested `!.agents/docs/CODE_MAP.md` line itself.
    lines = (REPO_ROOT / ".gitignore").read_text().splitlines()
    unignored = {ln.removeprefix("!.agents/") for ln in lines if ln.startswith("!.agents/")}
    reignored_dirs = {
        ln.removeprefix(".agents/").removesuffix("/*")
        for ln in lines
        if ln.startswith(".agents/") and ln.endswith("/*") and ln != ".agents/*"
    }
    committed = unignored - reignored_dirs
    assert set(sync_claude_dir.MIRRORED) == committed


def test_claude_settings_points_at_canonical_agents_hooks():
    # The mirrored settings.json must resolve hooks to the canonical .agents/
    # tree (works whether Claude reads .claude/ or .agents/), never a stale
    # .claude/hooks path.
    settings = (REPO_ROOT / ".claude" / "settings.json").read_text()
    assert ".agents/hooks/" in settings
    assert ".claude/hooks/" not in settings
