"""Deterministic AIBOM generation for the governance overlay (ADR-018, #412).

Emits ``.claude/governance/ai-bom.generated.md`` — an AI Bill of Materials the
scaffolder can *derive*: the installed MCP servers (from the MCP catalog over the
recorded selection) and the models CCR is configured to route to (from the
``multi_model`` overlay's ``config.json``, when present), labelled "detected CCR
routes". No LLM (ADR-001); regenerated on every scaffold/upgrade so it never
drifts, exactly like ``capabilities.emit`` (it is "always (over)written").

What the scaffolder *cannot* see — models/APIs a project calls directly (e.g. a
direct Anthropic SDK call) — lives in the user-owned ``ai-declarations.md``,
which is seeded once and preserved. The two files are never mixed: this one is
generated, that one is hand-maintained.
"""

from __future__ import annotations

import json
from pathlib import Path

from project_init.mcps import MCP_CATALOG, PLAYWRIGHT_MCP, servers_for_ids

_OUTPUT_REL = Path(".claude/governance/ai-bom.generated.md")
_CCR_CONFIG_REL = Path(".claude/multi-model/config.json")

_GENERATED_HEADER = (
    "<!-- Generated by project-init (ADR-018). Do not edit by hand — this file "
    "is overwritten on every scaffold/upgrade. Hand-declared models/APIs belong "
    "in ai-declarations.md. -->"
)


def _mcp_ids(variables: dict[str, str]) -> list[str]:
    raw = variables.get("installed_mcps", "none")
    if raw in ("", "none"):
        return []
    return [s.strip() for s in raw.split(",") if s.strip()]


def _server_transport(spec: dict) -> str:
    """One-line transport description for an MCP server spec."""
    if spec.get("type") == "http" or spec.get("url"):
        return f"http: {spec.get('url', '')}".strip()
    cmd = spec.get("command", "")
    args = " ".join(spec.get("args", []) or [])
    return f"stdio: {cmd} {args}".strip()


def extract_ccr_routes(config_path: Path) -> dict[str, list]:
    """Parse a claude-code-router ``config.json`` into detected routes.

    Returns ``{"routes": [(role, provider, model), ...], "providers": [name]}``.
    Empty (not an error) when the file is absent or unparseable — the
    ``multi_model`` overlay may simply not be installed. The ``Router`` map holds
    ``"provider,model"`` strings keyed by role plus a numeric
    ``longContextThreshold`` that is intentionally skipped (not a route).
    """
    try:
        data = json.loads(config_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError, ValueError):
        return {"routes": [], "providers": []}
    routes: list[tuple[str, str, str]] = []
    router = data.get("Router", {})
    if isinstance(router, dict):
        for role, value in router.items():
            if isinstance(value, str) and "," in value:
                provider, _, model = value.partition(",")
                routes.append((role, provider.strip(), model.strip()))
    providers: list[str] = []
    for prov in data.get("Providers", []) or []:
        if isinstance(prov, dict) and prov.get("name"):
            providers.append(str(prov["name"]))
    return {"routes": routes, "providers": providers}


def render_aibom(target: Path, variables: dict[str, str]) -> str:
    """Build the AIBOM markdown from the recorded selection + emitted overlays."""
    by_id = {m["id"]: m for m in MCP_CATALOG}
    by_id[PLAYWRIGHT_MCP["id"]] = PLAYWRIGHT_MCP
    servers = servers_for_ids(_mcp_ids(variables))

    lines: list[str] = [
        _GENERATED_HEADER,
        "",
        "# AI Bill of Materials (AIBOM)",
        "",
        "The AI components this project ships that `project-init` can detect. "
        "Models and APIs called directly (which no config reveals) are recorded "
        "by hand in [`ai-declarations.md`](ai-declarations.md).",
        "",
        "## MCP servers (installed)",
        "",
    ]
    if servers:
        lines += ["| ID | Name | Transport |", "|---|---|---|"]
        for mcp_id, spec in sorted(servers.items()):
            name = by_id.get(mcp_id, {}).get("name", mcp_id)
            lines.append(f"| `{mcp_id}` | {name} | {_server_transport(spec)} |")
    else:
        lines.append("_None installed._")
    lines += ["", "## Detected CCR routes", ""]

    if variables.get("multi_model"):
        ccr = extract_ccr_routes(target / _CCR_CONFIG_REL)
        if ccr["routes"]:
            lines += ["| Role | Provider | Model |", "|---|---|---|"]
            for role, provider, model in ccr["routes"]:
                lines.append(f"| {role} | {provider} | `{model}` |")
            lines += ["", f"_Providers configured: {', '.join(ccr['providers'])}._"]
        else:
            lines.append("_Multi-model overlay present but no routes detected._")
    else:
        lines.append(
            "_Multi-model (CCR) overlay not installed — no routed models to detect. "
            "Record directly-called models in [`ai-declarations.md`](ai-declarations.md)._"
        )
    lines.append("")
    return "\n".join(lines)


def emit(target: Path, variables: dict[str, str]) -> list[Path]:
    """Write ``.claude/governance/ai-bom.generated.md`` (always overwritten)."""
    dest = target / _OUTPUT_REL
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(render_aibom(target, variables), encoding="utf-8", newline="\n")
    return [_OUTPUT_REL]
