"""Core scaffolding logic — pure functions, no user interaction."""

from __future__ import annotations

import fnmatch
import json
import re
import shutil
import tomllib
from pathlib import Path

_PACKAGE_DIR = Path(__file__).resolve().parent
_TEMPLATES_DIR = _PACKAGE_DIR / "templates"
if not _TEMPLATES_DIR.exists():
    # Dev mode: templates live at repo root, not inside the package.
    _TEMPLATES_DIR = _PACKAGE_DIR.parent.parent / "templates"

_DOT_PREFIX = "dot_"
_VAR_RE = re.compile(r"\{\{(\w+)\}\}")
# Matches an INNERMOST conditional block — the tempered dot forbids another
# opener inside the body. _render loops to a fixpoint, so nested
# {{#if outer}}...{{#if inner}}...{{/if}}...{{/if}} resolves inside-out.
# A named closing tag must match the opener via the \1 backreference, so
# {{#if x}}...{{/if y}} does NOT match — it's left unrendered (strict mode then
# flags it) instead of silently gating on x and ignoring the typo'd y (PI-205).
_BLOCK_RE = re.compile(
    r"\{\{#if\s+(\w+)\}\}((?:(?!\{\{#if\s).)*?)\{\{/if(?:\s+\1)?\}\}",
    re.DOTALL,
)
# Used by strict mode to detect unrendered handlebars-style markers.
# The (?<!\$) negative lookbehind exempts GitHub Actions expressions (${{ ... }}).
_ANY_PLACEHOLDER_RE = re.compile(r"(?<!\$)\{\{[^}]+\}\}")

# Paths under these dirs are never overwritten on re-run (idempotency).
_PRESERVE_DIRS = {"memory", "vault"}
# Except READMEs — those are always refreshed.
_ALWAYS_OVERWRITE = {"README.md"}
# The owner-edited record file. On a re-scaffold it is preserved (not re-rendered)
# once it carries the scaffold record, so hand-edits — preserve list, project_key,
# declined_additions, safety.allow — survive (#296); write_scaffold_record then
# updates the record block in place. A first scaffold (no record) renders it.
_CONFIG_REL = Path(".claude/config.yaml")
# Marker that write_scaffold_record (upgrade.py) appends to .claude/config.yaml
# after a real project-init scaffold. Its PRESENCE — not the file merely
# existing — distinguishes a re-run from a first scaffold (PI-196).
_RECORD_MARKER = (
    "# --- scaffold record (generated by project-init; used by `project-init upgrade`) ---"
)


class TemplateRenderError(Exception):
    """Raised in strict mode when unrendered placeholders survive scaffolding."""


def list_presets() -> list[dict]:
    """Return all available presets as parsed dicts, sorted by name."""
    presets_dir = _TEMPLATES_DIR / "presets"
    results = []
    for p in sorted(presets_dir.glob("*.toml")):
        with p.open("rb") as f:
            results.append(tomllib.load(f))
    return results


def _version_tuple(value: str) -> tuple[int, int, int]:
    m = re.match(r"v?(\d+)\.(\d+)\.(\d+)", str(value or ""))
    return (int(m[1]), int(m[2]), int(m[3])) if m else (0, 0, 0)


def _merge_deps(parent: dict, child: dict) -> dict:
    """Union ``scaffolded_project_dependencies`` per language and core/dev kind."""
    merged = {lang: {k: list(v) for k, v in spec.items()} for lang, spec in parent.items()}
    for lang, spec in child.items():
        dest = merged.setdefault(lang, {})
        for kind, deps in spec.items():
            existing = dest.setdefault(kind, [])
            existing.extend(d for d in deps if d not in existing)
    return merged


def _merge_presets(parent: dict, child: dict) -> dict:
    """Merge a child preset onto its parent (#252).

    Layers append + dedup; vars and deps union with the child winning; other keys
    (name/description/markers) are overridden by the child.
    """
    merged = dict(parent)
    for key, value in child.items():
        if key not in ("layers", "vars", "extends", "scaffolded_project_dependencies"):
            merged[key] = value
    layers = list(parent.get("layers", []))
    layers.extend(layer for layer in child.get("layers", []) if layer not in layers)
    merged["layers"] = layers
    merged["vars"] = {**parent.get("vars", {}), **child.get("vars", {})}
    merged["scaffolded_project_dependencies"] = _merge_deps(
        parent.get("scaffolded_project_dependencies", {}),
        child.get("scaffolded_project_dependencies", {}),
    )
    merged.pop("extends", None)
    return merged


def _check_preset_compat(preset: dict) -> None:
    """Enforce a preset's ``min_project_init_version`` compat marker (#252)."""
    minimum = preset.get("min_project_init_version")
    if not minimum:
        return
    from project_init import __version__

    if _version_tuple(__version__) < _version_tuple(minimum):
        msg = (
            f"preset {preset.get('name')!r} requires project-init >= {minimum} "
            f"(installed {__version__}) — update project-init first."
        )
        raise ValueError(msg)


def load_preset(name: str, _seen: tuple[str, ...] = ()) -> dict:
    """Load a preset by name, resolving ``extends`` inheritance (#252).

    A company preset may ``extends`` a base preset; layers/vars/deps merge with
    the child winning. Cycles raise, and a ``min_project_init_version`` marker is
    enforced after merge.
    """
    presets_dir = _TEMPLATES_DIR / "presets"
    path = presets_dir / f"{name}.toml"
    # A preset name is a bare stem, never a path — reject traversal so a value
    # like `--preset ../../x` can't read a .toml outside presets/ (PI-188).
    safe_name = bool(name) and not ({"/", "\\"} & set(name)) and ".." not in name
    if not safe_name or path.resolve().parent != presets_dir.resolve() or not path.exists():
        available = [p.stem for p in sorted(presets_dir.glob("*.toml"))]
        msg = f"Unknown preset {name!r}. Available: {', '.join(available)}"
        raise ValueError(msg)
    with path.open("rb") as f:
        preset = tomllib.load(f)
    parent_name = preset.get("extends")
    if parent_name:
        if parent_name == name or parent_name in _seen:
            chain = " -> ".join([*_seen, name, parent_name])
            raise ValueError(f"circular preset extends: {chain}")
        preset = _merge_presets(load_preset(parent_name, (*_seen, name)), preset)
    _check_preset_compat(preset)
    return preset


def _toml_str(value: str) -> str:
    """Serialize *value* as an escaped TOML basic string (tomllib has no dumper)."""
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def generate_preset(name: str, *, extends: str, description: str = "", version: str = "") -> Path:
    """Write a starter company preset that extends *extends* (#252).

    Returns the written path. The parent must resolve (catches typos up front),
    and an existing preset is never clobbered. The name must be a safe slug; all
    interpolated values are TOML-escaped so quotes can't corrupt the file.
    """
    if not re.match(r"^[A-Za-z0-9._-]+$", name or ""):
        raise ValueError(f"invalid preset name {name!r} — use letters, digits, '.', '_', '-'")
    load_preset(extends)  # validates the base exists + is compatible
    path = _TEMPLATES_DIR / "presets" / f"{name}.toml"
    if path.exists():
        raise ValueError(f"preset {name!r} already exists at {path}")
    desc = description or f"Company preset extending {extends}."
    lines = [
        f"# Company preset: {name} (generated by project-init, #252)",
        f"name = {_toml_str(name)}",
        f"description = {_toml_str(desc)}",
        f"extends = {_toml_str(extends)}",
    ]
    if version:
        lines.append(f"min_project_init_version = {_toml_str(version)}")
    lines += [
        "",
        "[vars]",
        "# Override or add template variables here (child wins over the parent).",
        "",
        "[scaffolded_project_dependencies.python]",
        "core = []",
        "dev = []",
        "",
    ]
    # newline="\n" keeps rendered output LF even if the scaffolder runs on a
    # native-Windows Python (PI-362). No effect under WSL/macOS.
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    return path


# Agents whose native wiring ships as a template layer (PI-137); ollama is
# instructions-level only. Antigravity ships .agents/skills via this layer and its
# hooks/MCP via surfaces.py (PI-386). Single source for scaffold + upgrade (PI-189).
_AGENT_LAYERS = ("codex", "antigravity")


def overlay_layers(
    agents: str | list[str], *, no_plugin: bool, multi_model: bool = False
) -> list[str]:
    """Extra template layers appended to a preset beyond its base definition.

    The per-agent overlays (PI-137), prefixed with the ``fallback`` layer when
    plugins are off, plus the opt-in ``multi_model`` overlay (ADR-016, #351).
    One source for both the scaffolder and the ``upgrade`` re-render, so they can
    never derive a different layer set (PI-189).
    """
    chosen = {a.strip() for a in (agents.split(",") if isinstance(agents, str) else agents)}
    extra = [a for a in _AGENT_LAYERS if a in chosen]
    if no_plugin:
        extra = ["fallback", *extra]
    if multi_model:
        extra = [*extra, "multi_model"]
    return extra


def marketplace_source_vars(repo_url: str) -> dict[str, str]:
    """Host-aware plugin-marketplace source fields for settings.json (ADR-013, #248).

    Claude Code's ``source: github`` shorthand resolves only on public github.com;
    other hosts (GHES, GHE.com) need a full git URL. Returns the template flags +
    values so the scaffolded marketplace points at the fork's actual host instead
    of assuming github.com — which the old ``removeprefix("https://github.com/")``
    silently broke (left a full URL in an ``owner/repo`` field).
    """
    host = re.sub(r"^[a-zA-Z][\w+.-]*://", "", repo_url)  # strip scheme
    host = re.sub(r"^[^@/]*@", "", host)  # strip userinfo (e.g. git@)
    host = re.split(r"[/:]", host, maxsplit=1)[0]
    slug = re.sub(r"\.git$", "", repo_url.rstrip("/"))
    slug = re.sub(r"^.*[/:]([^/]+/[^/]+)$", r"\1", slug)
    is_github = host == "github.com"
    url = repo_url if repo_url.endswith(".git") else f"{repo_url}.git"
    return {
        "project_init_repo": slug,  # owner/repo — github source + display
        "project_init_repo_url": url,  # full clone URL — git source (non-github hosts)
        "project_init_host": host or "github.com",  # observability record (#259)
        "project_init_github": "true" if is_github else "",
        "project_init_enterprise": "" if is_github else "true",
    }


def _render(text: str, variables: dict[str, str]) -> str:
    """Replace {{var}} placeholders and process {{#if var}}...{{/if var}} blocks.

    Conditional blocks may nest; each pass substitutes the innermost blocks,
    looping until no block remains (unclosed markers survive for strict mode
    to flag).
    """

    def _replace_block(m: re.Match) -> str:
        key = m.group(1)
        return m.group(2) if variables.get(key) else ""

    while True:
        replaced = _BLOCK_RE.sub(_replace_block, text)
        if replaced == text:
            break
        text = replaced
    # Then simple variable substitution.
    return _VAR_RE.sub(lambda m: variables.get(m.group(1), m.group(0)), text)


def _dot_rename(name: str) -> str:
    """Rename 'dot_foo' to '.foo'."""
    if name.startswith(_DOT_PREFIX):
        return "." + name[len(_DOT_PREFIX) :]
    return name


def read_preserve_globs(target: Path) -> list[str]:
    """User-declared extra preserve globs from ``.claude/config.yaml`` (#243).

    Reads a single-line ``preserve: ["a", "b/*"]`` JSON array (a valid YAML flow
    sequence, parseable with stdlib — consistent with the scaffold record's
    single-line JSON values). Returns ``[]`` when the file or key is absent or
    malformed; the built-in ``memory``/``vault`` defaults always apply on top.
    """
    config = target / ".claude" / "config.yaml"
    try:
        text = config.read_text(encoding="utf-8")
    except OSError:
        return []
    # Greedy capture to the last ``]`` so globs with fnmatch character classes
    # (e.g. ``file[0-9].txt``) are not truncated at an inner ``]`` (PR #295 review).
    m = re.search(r"^[ \t]*preserve:[ \t]*(\[.*\])[ \t]*(?:#.*)?$", text, re.MULTILINE)
    if not m:
        return []
    try:
        value = json.loads(m.group(1))
    except json.JSONDecodeError:
        return []
    return [str(p) for p in value] if isinstance(value, list) else []


def _matches_preserve_glob(rel: Path, globs: list[str]) -> bool:
    """True if *rel* matches any user preserve glob (#243).

    Tests the full posix path, the bare filename, and a directory prefix, so
    ``ci.yml`` also catches a nested ``.github/workflows/ci.yml``, ``docs/*.md``
    is a path glob, and ``build`` preserves the whole ``build/`` subtree.
    """
    posix = rel.as_posix()
    for raw in globs:
        pat = raw.strip()
        if pat and (
            fnmatch.fnmatch(posix, pat)
            or fnmatch.fnmatch(rel.name, pat)
            or posix.startswith(pat.rstrip("/") + "/")
        ):
            return True
    return False


def _should_preserve(rel_path: Path, target: Path, preserve_globs: list[str] | None = None) -> bool:
    """Return True if this file should be skipped on re-run.

    Built-in ``memory``/``vault`` dirs plus any user-declared *preserve_globs*
    (#243) are protected; READMEs are always refreshed.
    """
    dest = target / rel_path
    if not dest.exists():
        return False
    if rel_path.name in _ALWAYS_OVERWRITE:
        return False
    # A re-scaffold must not clobber a hand-edited config.yaml that already
    # carries a scaffold record (#296); write_scaffold_record updates the record
    # block in place afterwards. A first scaffold (no record) still renders it.
    if rel_path == _CONFIG_REL and _has_scaffold_record(dest):
        return True
    if any(part in _PRESERVE_DIRS for part in rel_path.parts):
        return True
    return _matches_preserve_glob(rel_path, preserve_globs or [])


def _rendered_bytes(src: Path, variables: dict[str, str], is_template: bool) -> bytes | None:
    """Return the bytes scaffolding would write for *src*, or None if skipped.

    Mirrors :func:`_emit_file`'s content rules without touching the filesystem,
    so callers can compare against an existing file before deciding to write.
    """
    if is_template:
        rendered = _render(src.read_text(encoding="utf-8"), variables)
        if not rendered.strip():
            return None
        return rendered.encode("utf-8")
    return src.read_bytes()


def _write_bytes(dest: Path, content: bytes, src: Path) -> None:
    """Write *content* to *dest*, preserving *src*'s executable bit."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_bytes(content)
    if src.stat().st_mode & 0o111:
        dest.chmod(dest.stat().st_mode | 0o111)


def _new_sibling(dest: Path, content: bytes) -> Path:
    """Pick a ``.new`` sibling path for a file we must not overwrite (PI-179).

    Mirrors the upgrade conflict convention: an existing ``.new`` may hold a
    user's in-progress merge, so reuse it only when its content already equals
    the fresh render; otherwise take ``.new.1``, ``.new.2``, …
    """
    candidate = dest.parent / (dest.name + ".new")
    counter = 0
    while candidate.exists() and candidate.read_bytes() != content:
        counter += 1
        candidate = dest.parent / (dest.name + f".new.{counter}")
    return candidate


def _has_pending_sibling(dest: Path) -> bool:
    """True if an unresolved ``.new``/``.new.N`` sibling already exists for *dest*.

    A pending sibling means a prior scaffold preserved this file and the user
    has not merged it yet, so a re-run must keep protecting it (PI-179).
    """
    base = dest.name + ".new"
    return (dest.parent / base).exists() or any(
        p.name.startswith(base + ".") for p in dest.parent.glob(dest.name + ".new.*")
    )


def _protected_as_sibling(
    src: Path, dest: Path, variables: dict[str, str], is_template: bool, *, first: bool
) -> Path | None:
    """Write the fresh render beside *dest* instead of overwriting it (PI-179).

    Returns the ``.new`` sibling path written when *dest* is a user-owned file
    that must be protected — i.e. it exists with content differing from the
    render, and either this is the *first* scaffold or an unresolved sibling
    from an earlier run is still pending (so a re-run does not clobber a file
    the user has not merged). Returns None when the normal write should proceed.
    """
    if not dest.exists() or not (first or _has_pending_sibling(dest)):
        return None
    content = _rendered_bytes(src, variables, is_template)
    if content is None or dest.read_bytes() == content:
        return None
    sibling = _new_sibling(dest, content)
    _write_bytes(sibling, content, src)
    return sibling


def _output_rel_path(src: Path, layer_dir: Path) -> tuple[Path, bool]:
    """Map a template source file to its output-relative path.

    Renames ``dot_`` segments to dotfiles and strips the ``.tmpl`` suffix.
    Returns the relative path and whether the file is a render template.
    """
    rel_parts = [_dot_rename(p) for p in src.relative_to(layer_dir).parts]
    is_template = rel_parts[-1].endswith(".tmpl")
    if is_template:
        rel_parts[-1] = rel_parts[-1][: -len(".tmpl")]
    return Path(*rel_parts), is_template


def _emit_file(
    src: Path,
    dest: Path,
    variables: dict[str, str],
    is_template: bool,
) -> str | None:
    """Write one template file to *dest*; return rendered text for .tmpl files.

    Returns None when the file was skipped: a template whose rendered output
    is empty or whitespace-only is not created at all. Wrapping an entire
    .tmpl file in ``{{#if lang}}...{{/if}}`` therefore makes the file itself
    conditional on that variable.
    """
    if is_template:
        rendered = _render(src.read_text(encoding="utf-8"), variables)
        if not rendered.strip():
            return None
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(rendered, encoding="utf-8", newline="\n")  # LF on all hosts (PI-362)
    else:
        rendered = ""
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)

    # Preserve executable bit.
    if src.stat().st_mode & 0o111:
        dest.chmod(dest.stat().st_mode | 0o111)
    return rendered


def _validate_no_placeholders(rendered_files: list[tuple[Path, str]]) -> None:
    """Raise TemplateRenderError if any rendered file kept a ``{{...}}`` marker."""
    offenders: list[str] = []
    for rel_path, content in rendered_files:
        for match in _ANY_PLACEHOLDER_RE.finditer(content):
            offenders.append(f"{rel_path}: {match.group()}")
    if offenders:
        msg = "strict mode: unrendered placeholders survived scaffolding:\n  " + "\n  ".join(
            offenders
        )
        raise TemplateRenderError(msg)


def _iter_layer_files(layers: list[str]):
    """Yield (src, layer_dir) for every file across the preset's template layers."""
    for layer_name in layers:
        layer_dir = _TEMPLATES_DIR / layer_name
        if not layer_dir.exists():
            msg = f"Template layer {layer_name!r} not found at {layer_dir}"
            raise FileNotFoundError(msg)
        for src in sorted(layer_dir.rglob("*")):
            if src.is_dir():
                continue
            yield src, layer_dir


def _commit_staged(
    work_dir: Path,
    target: Path,
    staged: list[Path],
    *,
    first: bool = False,
    conflicts: list[tuple[Path, Path]] | None = None,
) -> list[Path]:
    """Copy validated files from the strict-mode staging dir into *target*.

    Honors rerun idempotency: user-owned memory/vault files are not overwritten.
    When a *conflicts* list is passed (protection, PI-179), a user-owned file
    with different content is kept and the fresh render lands as a ``.new``
    sibling. A file is user-owned on the *first* scaffold, or on any run while an
    unresolved sibling from an earlier run is still pending. Each protected file
    is recorded as ``(original_rel, sibling_rel)``.
    """
    created: list[Path] = []
    target.mkdir(parents=True, exist_ok=True)
    preserve_globs = read_preserve_globs(target)
    for rel_path in staged:
        if _should_preserve(rel_path, target, preserve_globs):
            continue
        src = work_dir / rel_path
        dest = target / rel_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        protect = conflicts is not None and (first or _has_pending_sibling(dest))
        if protect and dest.exists() and dest.read_bytes() != src.read_bytes():
            sibling = _new_sibling(dest, src.read_bytes())
            shutil.copy2(src, sibling)
            conflicts.append((rel_path, sibling.relative_to(target)))
            continue
        shutil.copy2(src, dest)
        created.append(rel_path)
    return created


def _has_scaffold_record(config_file: Path) -> bool:
    """Return True if .claude/config.yaml carries the scaffold record marker.

    A read failure (permissions, or the file removed between the check and the
    read) is treated as "no record" so overwrite protection stays on and user
    files are preserved rather than aborting the scaffold (PI-196 review).
    """
    try:
        return config_file.exists() and (
            _RECORD_MARKER in config_file.read_text(encoding="utf-8", errors="ignore")
        )
    except OSError:
        return False


def scaffold(
    target: Path,
    preset: dict,
    variables: dict[str, str],
    *,
    strict: bool = False,
    conflicts: list[tuple[Path, Path]] | None = None,
) -> list[Path]:
    """Copy + render template layers into *target*. Return created file paths.

    A .tmpl file whose rendered output is empty or whitespace-only is skipped
    entirely (see :func:`_emit_file`) — this is how language-specific config
    files are made conditional.

    When *strict* is True, raise :class:`TemplateRenderError` if any
    ``{{...}}`` placeholder or unclosed conditional survives rendering.

    In strict mode, all output is written to a temporary directory first.
    Only on successful validation are rendered files committed to target.

    Passing a *conflicts* list turns on overwrite protection (PI-179): a
    user-owned file whose content differs from the fresh render is never
    overwritten — the render is written as a ``<file>.new`` sibling and the pair
    ``(original_rel, sibling_rel)`` is appended to *conflicts*. A file counts as
    user-owned on the first scaffold (no recorded ``config.yaml``) or, on any
    later run, while an unresolved sibling from an earlier run is still pending —
    so a re-run never clobbers a file the user has not merged yet. memory/vault
    preservation is unchanged either way.
    """
    import uuid

    # A pre-existing .claude/config.yaml only proves a prior project-init run
    # when it carries the scaffold record marker; a hand-written or third-party
    # config.yaml must still count as a first scaffold so existing user files are
    # protected as `.new` siblings rather than silently overwritten (PI-196).
    _config_file = target / ".claude" / "config.yaml"
    first_scaffold = not _has_scaffold_record(_config_file)
    preserve_globs = read_preserve_globs(target)

    layers: list[str] = preset["layers"]
    created: list[Path] = []
    staged: list[Path] = []
    written: set[Path] = set()  # paths this run has emitted (later layers may overwrite)
    rendered_files: list[tuple[Path, str]] = []  # for strict-mode scan

    # For strict mode: write to temp, validate, then copy into target.
    # Non-strict: write directly to target (best-effort behavior acceptable per PI-21).
    if strict:
        # Use a temp directory under target.parent so staged files are close to
        # the final target. UUID suffix prevents collisions.
        temp_suffix = f".partial-{uuid.uuid4().hex[:8]}"
        work_dir = target.parent / (target.name + temp_suffix)
    else:
        work_dir = target
    work_dir.mkdir(parents=True, exist_ok=True)

    try:
        for src, layer_dir in _iter_layer_files(layers):
            rel_path, is_template = _output_rel_path(src, layer_dir)

            # For non-strict mode, check preservation against the actual target.
            # For strict mode, we're writing to temp, so skip preservation check.
            if not strict and _should_preserve(rel_path, target, preserve_globs):
                continue

            # Overwrite protection (non-strict; strict handles it at commit time
            # in _commit_staged): never clobber a user-owned file — write the
            # render as a `.new` sibling instead (PI-179). Skip when an earlier
            # layer of THIS run already wrote the path: later layers legitimately
            # overwrite earlier ones, that is not a user file. work_dir == target
            # in non-strict mode, so dest is the real file.
            if (
                not strict
                and conflicts is not None
                and rel_path not in written
                and (
                    sibling := _protected_as_sibling(
                        src, work_dir / rel_path, variables, is_template, first=first_scaffold
                    )
                )
                is not None
            ):
                conflicts.append((rel_path, rel_path.parent / sibling.name))
                continue

            rendered = _emit_file(src, work_dir / rel_path, variables, is_template)
            if rendered is None:
                continue
            if is_template and strict:
                rendered_files.append((rel_path, rendered))
            (staged if strict else created).append(rel_path)
            written.add(rel_path)

        if strict:
            _validate_no_placeholders(rendered_files)
            created = _commit_staged(
                work_dir, target, staged, first=first_scaffold, conflicts=conflicts
            )
            shutil.rmtree(work_dir)

    except Exception:
        # On any error (validation or I/O), clean up temp directory in strict mode.
        if strict and work_dir.exists():
            shutil.rmtree(work_dir)
        raise

    # Per-surface config generation (ADR-017 / PI-366): emit hooks + MCP for the
    # selected GUI surfaces from the canonical surface table + MCP catalog. Runs
    # against the committed target (after _commit_staged in strict mode).
    from project_init import surfaces
    from project_init.mcps import servers_for_ids

    agents = [a.strip() for a in variables.get("agents", "").split(",") if a.strip()]
    mcp_raw = variables.get("installed_mcps", "none")
    mcp_ids = (
        []
        if mcp_raw in ("", "none")
        else [s.strip() for s in mcp_raw.split(",") if s.strip()]
    )
    created += surfaces.emit(
        target,
        agents=agents,
        servers=servers_for_ids(mcp_ids),
        conflicts=conflicts,
    )

    # Surface-independent capabilities inventory (PI-374): a generated
    # CAPABILITIES.md derived from the canonical skill/hook/MCP sources + the
    # chosen options, regenerated each run so it never drifts.
    from project_init import capabilities

    created += capabilities.emit(target, variables)

    return created
